// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"github.com/patrhez/agent-platform/backend/internal/model"
	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"
)

func newArtifact(db *gorm.DB, opts ...gen.DOOption) artifact {
	_artifact := artifact{}

	_artifact.artifactDo.IWithDO = gen.WithDOFunc[IArtifactDo](_artifact.artifactDo.withDO)

	_artifact.artifactDo.UseDB(db, opts...)
	_artifact.artifactDo.UseModel(&model.Artifact{})

	tableName := _artifact.artifactDo.TableName()
	_artifact.ALL = field.NewAsterisk(tableName)
	_artifact.ID = field.NewString(tableName, "id")
	_artifact.RunID = field.NewString(tableName, "run_id")
	_artifact.Kind = field.NewString(tableName, "kind")
	_artifact.ContentType = field.NewString(tableName, "content_type")
	_artifact.Content = field.NewBytes(tableName, "content")
	_artifact.SHA256 = field.NewString(tableName, "sha256")
	_artifact.ByteSize = field.NewInt64(tableName, "byte_size")
	_artifact.CreatedAt = field.NewTime(tableName, "created_at")

	_artifact.fillFieldMap()

	return _artifact
}

type artifact struct {
	artifactDo artifactDo

	ALL         field.Asterisk
	ID          field.String
	RunID       field.String
	Kind        field.String
	ContentType field.String
	Content     field.Bytes
	SHA256      field.String
	ByteSize    field.Int64
	CreatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (a artifact) Table(newTableName string) *artifact {
	a.artifactDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a artifact) As(alias string) *artifact {
	a.artifactDo.DO = *(a.artifactDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *artifact) updateTableName(table string) *artifact {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewString(table, "id")
	a.RunID = field.NewString(table, "run_id")
	a.Kind = field.NewString(table, "kind")
	a.ContentType = field.NewString(table, "content_type")
	a.Content = field.NewBytes(table, "content")
	a.SHA256 = field.NewString(table, "sha256")
	a.ByteSize = field.NewInt64(table, "byte_size")
	a.CreatedAt = field.NewTime(table, "created_at")

	a.fillFieldMap()

	return a
}

func (a *artifact) WithContext(ctx context.Context) IArtifactDo { return a.artifactDo.WithContext(ctx) }

func (a artifact) TableName() string { return a.artifactDo.TableName() }

func (a artifact) Alias() string { return a.artifactDo.Alias() }

func (a artifact) Columns(cols ...field.Expr) gen.Columns { return a.artifactDo.Columns(cols...) }

func (a *artifact) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *artifact) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 8)
	a.fieldMap["id"] = a.ID
	a.fieldMap["run_id"] = a.RunID
	a.fieldMap["kind"] = a.Kind
	a.fieldMap["content_type"] = a.ContentType
	a.fieldMap["content"] = a.Content
	a.fieldMap["sha256"] = a.SHA256
	a.fieldMap["byte_size"] = a.ByteSize
	a.fieldMap["created_at"] = a.CreatedAt
}

func (a artifact) clone(db *gorm.DB) artifact {
	a.artifactDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a artifact) replaceDB(db *gorm.DB) artifact {
	a.artifactDo.ReplaceDB(db)
	return a
}

type artifactDo struct {
	gen.GenericsDo[IArtifactDo, *model.Artifact]
}
type IArtifactDo interface {
	gen.IGenericsDo[IArtifactDo, *model.Artifact]
}

func (a *artifactDo) withDO(do gen.Dao) IArtifactDo {
	_r := &artifactDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IArtifactDo](a.withDO)
	return _r
}
