// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"github.com/patrhez/agent-platform/backend/internal/model"
	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"
)

func newConversation(db *gorm.DB, opts ...gen.DOOption) conversation {
	_conversation := conversation{}

	_conversation.conversationDo.IWithDO = gen.WithDOFunc[IConversationDo](_conversation.conversationDo.withDO)

	_conversation.conversationDo.UseDB(db, opts...)
	_conversation.conversationDo.UseModel(&model.Conversation{})

	tableName := _conversation.conversationDo.TableName()
	_conversation.ALL = field.NewAsterisk(tableName)
	_conversation.ID = field.NewString(tableName, "id")
	_conversation.UserID = field.NewString(tableName, "user_id")
	_conversation.Title = field.NewString(tableName, "title")
	_conversation.NextMessageSeq = field.NewInt64(tableName, "next_message_seq")
	_conversation.NextRunSeq = field.NewInt64(tableName, "next_run_seq")
	_conversation.NextExecutableRunSeq = field.NewInt64(tableName, "next_executable_run_seq")
	_conversation.DeletedAt = field.NewField(tableName, "deleted_at")
	_conversation.CreatedAt = field.NewTime(tableName, "created_at")
	_conversation.UpdatedAt = field.NewTime(tableName, "updated_at")
	_conversation.LatestMessageAt = field.NewTime(tableName, "latest_message_at")

	_conversation.fillFieldMap()

	return _conversation
}

type conversation struct {
	conversationDo conversationDo

	ALL                  field.Asterisk
	ID                   field.String
	UserID               field.String
	Title                field.String
	NextMessageSeq       field.Int64
	NextRunSeq           field.Int64
	NextExecutableRunSeq field.Int64
	DeletedAt            field.Field
	CreatedAt            field.Time
	UpdatedAt            field.Time
	LatestMessageAt      field.Time

	fieldMap map[string]field.Expr
}

func (c conversation) Table(newTableName string) *conversation {
	c.conversationDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c conversation) As(alias string) *conversation {
	c.conversationDo.DO = *(c.conversationDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *conversation) updateTableName(table string) *conversation {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewString(table, "id")
	c.UserID = field.NewString(table, "user_id")
	c.Title = field.NewString(table, "title")
	c.NextMessageSeq = field.NewInt64(table, "next_message_seq")
	c.NextRunSeq = field.NewInt64(table, "next_run_seq")
	c.NextExecutableRunSeq = field.NewInt64(table, "next_executable_run_seq")
	c.DeletedAt = field.NewField(table, "deleted_at")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")
	c.LatestMessageAt = field.NewTime(table, "latest_message_at")

	c.fillFieldMap()

	return c
}

func (c *conversation) WithContext(ctx context.Context) IConversationDo {
	return c.conversationDo.WithContext(ctx)
}

func (c conversation) TableName() string { return c.conversationDo.TableName() }

func (c conversation) Alias() string { return c.conversationDo.Alias() }

func (c conversation) Columns(cols ...field.Expr) gen.Columns {
	return c.conversationDo.Columns(cols...)
}

func (c *conversation) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *conversation) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 10)
	c.fieldMap["id"] = c.ID
	c.fieldMap["user_id"] = c.UserID
	c.fieldMap["title"] = c.Title
	c.fieldMap["next_message_seq"] = c.NextMessageSeq
	c.fieldMap["next_run_seq"] = c.NextRunSeq
	c.fieldMap["next_executable_run_seq"] = c.NextExecutableRunSeq
	c.fieldMap["deleted_at"] = c.DeletedAt
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
	c.fieldMap["latest_message_at"] = c.LatestMessageAt
}

func (c conversation) clone(db *gorm.DB) conversation {
	c.conversationDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c conversation) replaceDB(db *gorm.DB) conversation {
	c.conversationDo.ReplaceDB(db)
	return c
}

type conversationDo struct {
	gen.GenericsDo[IConversationDo, *model.Conversation]
}
type IConversationDo interface {
	gen.IGenericsDo[IConversationDo, *model.Conversation]
}

func (c *conversationDo) withDO(do gen.Dao) IConversationDo {
	_r := &conversationDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IConversationDo](c.withDO)
	return _r
}
