// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q             = new(Query)
	Artifact      *artifact
	Conversation  *conversation
	Message       *message
	Run           *run
	RunCheckpoint *runCheckpoint
	RunEvent      *runEvent
	RunStep       *runStep
	ToolCall      *toolCall
	User          *user
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Artifact = &Q.Artifact
	Conversation = &Q.Conversation
	Message = &Q.Message
	Run = &Q.Run
	RunCheckpoint = &Q.RunCheckpoint
	RunEvent = &Q.RunEvent
	RunStep = &Q.RunStep
	ToolCall = &Q.ToolCall
	User = &Q.User
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:            db,
		Artifact:      newArtifact(db, opts...),
		Conversation:  newConversation(db, opts...),
		Message:       newMessage(db, opts...),
		Run:           newRun(db, opts...),
		RunCheckpoint: newRunCheckpoint(db, opts...),
		RunEvent:      newRunEvent(db, opts...),
		RunStep:       newRunStep(db, opts...),
		ToolCall:      newToolCall(db, opts...),
		User:          newUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Artifact      artifact
	Conversation  conversation
	Message       message
	Run           run
	RunCheckpoint runCheckpoint
	RunEvent      runEvent
	RunStep       runStep
	ToolCall      toolCall
	User          user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) UnderlyingDB() *gorm.DB { return q.db }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:            db,
		Artifact:      q.Artifact.clone(db),
		Conversation:  q.Conversation.clone(db),
		Message:       q.Message.clone(db),
		Run:           q.Run.clone(db),
		RunCheckpoint: q.RunCheckpoint.clone(db),
		RunEvent:      q.RunEvent.clone(db),
		RunStep:       q.RunStep.clone(db),
		ToolCall:      q.ToolCall.clone(db),
		User:          q.User.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:            db,
		Artifact:      q.Artifact.replaceDB(db),
		Conversation:  q.Conversation.replaceDB(db),
		Message:       q.Message.replaceDB(db),
		Run:           q.Run.replaceDB(db),
		RunCheckpoint: q.RunCheckpoint.replaceDB(db),
		RunEvent:      q.RunEvent.replaceDB(db),
		RunStep:       q.RunStep.replaceDB(db),
		ToolCall:      q.ToolCall.replaceDB(db),
		User:          q.User.replaceDB(db),
	}
}

type queryCtx struct {
	Artifact      IArtifactDo
	Conversation  IConversationDo
	Message       IMessageDo
	Run           IRunDo
	RunCheckpoint IRunCheckpointDo
	RunEvent      IRunEventDo
	RunStep       IRunStepDo
	ToolCall      IToolCallDo
	User          IUserDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Artifact:      q.Artifact.WithContext(ctx),
		Conversation:  q.Conversation.WithContext(ctx),
		Message:       q.Message.WithContext(ctx),
		Run:           q.Run.WithContext(ctx),
		RunCheckpoint: q.RunCheckpoint.WithContext(ctx),
		RunEvent:      q.RunEvent.WithContext(ctx),
		RunStep:       q.RunStep.WithContext(ctx),
		ToolCall:      q.ToolCall.WithContext(ctx),
		User:          q.User.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
