// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"github.com/patrhez/agent-platform/backend/internal/model"
	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"
)

func newMessage(db *gorm.DB, opts ...gen.DOOption) message {
	_message := message{}

	_message.messageDo.IWithDO = gen.WithDOFunc[IMessageDo](_message.messageDo.withDO)

	_message.messageDo.UseDB(db, opts...)
	_message.messageDo.UseModel(&model.Message{})

	tableName := _message.messageDo.TableName()
	_message.ALL = field.NewAsterisk(tableName)
	_message.ID = field.NewString(tableName, "id")
	_message.ConversationID = field.NewString(tableName, "conversation_id")
	_message.Seq = field.NewInt64(tableName, "seq")
	_message.Role = field.NewString(tableName, "role")
	_message.Content = field.NewString(tableName, "content")
	_message.Status = field.NewString(tableName, "status")
	_message.RunID = field.NewString(tableName, "run_id")
	_message.ClientMessageID = field.NewString(tableName, "client_message_id")
	_message.CreatedAt = field.NewTime(tableName, "created_at")
	_message.FinalizedAt = field.NewTime(tableName, "finalized_at")

	_message.fillFieldMap()

	return _message
}

type message struct {
	messageDo messageDo

	ALL             field.Asterisk
	ID              field.String
	ConversationID  field.String
	Seq             field.Int64
	Role            field.String
	Content         field.String
	Status          field.String
	RunID           field.String
	ClientMessageID field.String
	CreatedAt       field.Time
	FinalizedAt     field.Time

	fieldMap map[string]field.Expr
}

func (m message) Table(newTableName string) *message {
	m.messageDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m message) As(alias string) *message {
	m.messageDo.DO = *(m.messageDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *message) updateTableName(table string) *message {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewString(table, "id")
	m.ConversationID = field.NewString(table, "conversation_id")
	m.Seq = field.NewInt64(table, "seq")
	m.Role = field.NewString(table, "role")
	m.Content = field.NewString(table, "content")
	m.Status = field.NewString(table, "status")
	m.RunID = field.NewString(table, "run_id")
	m.ClientMessageID = field.NewString(table, "client_message_id")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.FinalizedAt = field.NewTime(table, "finalized_at")

	m.fillFieldMap()

	return m
}

func (m *message) WithContext(ctx context.Context) IMessageDo { return m.messageDo.WithContext(ctx) }

func (m message) TableName() string { return m.messageDo.TableName() }

func (m message) Alias() string { return m.messageDo.Alias() }

func (m message) Columns(cols ...field.Expr) gen.Columns { return m.messageDo.Columns(cols...) }

func (m *message) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *message) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 10)
	m.fieldMap["id"] = m.ID
	m.fieldMap["conversation_id"] = m.ConversationID
	m.fieldMap["seq"] = m.Seq
	m.fieldMap["role"] = m.Role
	m.fieldMap["content"] = m.Content
	m.fieldMap["status"] = m.Status
	m.fieldMap["run_id"] = m.RunID
	m.fieldMap["client_message_id"] = m.ClientMessageID
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["finalized_at"] = m.FinalizedAt
}

func (m message) clone(db *gorm.DB) message {
	m.messageDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m message) replaceDB(db *gorm.DB) message {
	m.messageDo.ReplaceDB(db)
	return m
}

type messageDo struct {
	gen.GenericsDo[IMessageDo, *model.Message]
}
type IMessageDo interface {
	gen.IGenericsDo[IMessageDo, *model.Message]
}

func (m *messageDo) withDO(do gen.Dao) IMessageDo {
	_r := &messageDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IMessageDo](m.withDO)
	return _r
}
