// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"github.com/patrhez/agent-platform/backend/internal/model"
	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"
)

func newRunCheckpoint(db *gorm.DB, opts ...gen.DOOption) runCheckpoint {
	_runCheckpoint := runCheckpoint{}

	_runCheckpoint.runCheckpointDo.IWithDO = gen.WithDOFunc[IRunCheckpointDo](_runCheckpoint.runCheckpointDo.withDO)

	_runCheckpoint.runCheckpointDo.UseDB(db, opts...)
	_runCheckpoint.runCheckpointDo.UseModel(&model.RunCheckpoint{})

	tableName := _runCheckpoint.runCheckpointDo.TableName()
	_runCheckpoint.ALL = field.NewAsterisk(tableName)
	_runCheckpoint.ID = field.NewString(tableName, "id")
	_runCheckpoint.RunID = field.NewString(tableName, "run_id")
	_runCheckpoint.Ordinal = field.NewInt(tableName, "ordinal")
	_runCheckpoint.RuntimeName = field.NewString(tableName, "runtime_name")
	_runCheckpoint.StateSchemaVersion = field.NewInt(tableName, "state_schema_version")
	_runCheckpoint.Payload = field.NewField(tableName, "payload")
	_runCheckpoint.CreatedAt = field.NewTime(tableName, "created_at")

	_runCheckpoint.fillFieldMap()

	return _runCheckpoint
}

type runCheckpoint struct {
	runCheckpointDo runCheckpointDo

	ALL                field.Asterisk
	ID                 field.String
	RunID              field.String
	Ordinal            field.Int
	RuntimeName        field.String
	StateSchemaVersion field.Int
	Payload            field.Field
	CreatedAt          field.Time

	fieldMap map[string]field.Expr
}

func (r runCheckpoint) Table(newTableName string) *runCheckpoint {
	r.runCheckpointDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r runCheckpoint) As(alias string) *runCheckpoint {
	r.runCheckpointDo.DO = *(r.runCheckpointDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *runCheckpoint) updateTableName(table string) *runCheckpoint {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewString(table, "id")
	r.RunID = field.NewString(table, "run_id")
	r.Ordinal = field.NewInt(table, "ordinal")
	r.RuntimeName = field.NewString(table, "runtime_name")
	r.StateSchemaVersion = field.NewInt(table, "state_schema_version")
	r.Payload = field.NewField(table, "payload")
	r.CreatedAt = field.NewTime(table, "created_at")

	r.fillFieldMap()

	return r
}

func (r *runCheckpoint) WithContext(ctx context.Context) IRunCheckpointDo {
	return r.runCheckpointDo.WithContext(ctx)
}

func (r runCheckpoint) TableName() string { return r.runCheckpointDo.TableName() }

func (r runCheckpoint) Alias() string { return r.runCheckpointDo.Alias() }

func (r runCheckpoint) Columns(cols ...field.Expr) gen.Columns {
	return r.runCheckpointDo.Columns(cols...)
}

func (r *runCheckpoint) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *runCheckpoint) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 7)
	r.fieldMap["id"] = r.ID
	r.fieldMap["run_id"] = r.RunID
	r.fieldMap["ordinal"] = r.Ordinal
	r.fieldMap["runtime_name"] = r.RuntimeName
	r.fieldMap["state_schema_version"] = r.StateSchemaVersion
	r.fieldMap["payload"] = r.Payload
	r.fieldMap["created_at"] = r.CreatedAt
}

func (r runCheckpoint) clone(db *gorm.DB) runCheckpoint {
	r.runCheckpointDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r runCheckpoint) replaceDB(db *gorm.DB) runCheckpoint {
	r.runCheckpointDo.ReplaceDB(db)
	return r
}

type runCheckpointDo struct {
	gen.GenericsDo[IRunCheckpointDo, *model.RunCheckpoint]
}
type IRunCheckpointDo interface {
	gen.IGenericsDo[IRunCheckpointDo, *model.RunCheckpoint]
}

func (r *runCheckpointDo) withDO(do gen.Dao) IRunCheckpointDo {
	_r := &runCheckpointDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IRunCheckpointDo](r.withDO)
	return _r
}
