// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"github.com/patrhez/agent-platform/backend/internal/model"
	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"
)

func newRunEvent(db *gorm.DB, opts ...gen.DOOption) runEvent {
	_runEvent := runEvent{}

	_runEvent.runEventDo.IWithDO = gen.WithDOFunc[IRunEventDo](_runEvent.runEventDo.withDO)

	_runEvent.runEventDo.UseDB(db, opts...)
	_runEvent.runEventDo.UseModel(&model.RunEvent{})

	tableName := _runEvent.runEventDo.TableName()
	_runEvent.ALL = field.NewAsterisk(tableName)
	_runEvent.ID = field.NewString(tableName, "id")
	_runEvent.RunID = field.NewString(tableName, "run_id")
	_runEvent.Seq = field.NewInt64(tableName, "seq")
	_runEvent.Type = field.NewString(tableName, "type")
	_runEvent.SafePayload = field.NewField(tableName, "safe_payload")
	_runEvent.CreatedAt = field.NewTime(tableName, "created_at")

	_runEvent.fillFieldMap()

	return _runEvent
}

type runEvent struct {
	runEventDo runEventDo

	ALL         field.Asterisk
	ID          field.String
	RunID       field.String
	Seq         field.Int64
	Type        field.String
	SafePayload field.Field
	CreatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (r runEvent) Table(newTableName string) *runEvent {
	r.runEventDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r runEvent) As(alias string) *runEvent {
	r.runEventDo.DO = *(r.runEventDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *runEvent) updateTableName(table string) *runEvent {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewString(table, "id")
	r.RunID = field.NewString(table, "run_id")
	r.Seq = field.NewInt64(table, "seq")
	r.Type = field.NewString(table, "type")
	r.SafePayload = field.NewField(table, "safe_payload")
	r.CreatedAt = field.NewTime(table, "created_at")

	r.fillFieldMap()

	return r
}

func (r *runEvent) WithContext(ctx context.Context) IRunEventDo { return r.runEventDo.WithContext(ctx) }

func (r runEvent) TableName() string { return r.runEventDo.TableName() }

func (r runEvent) Alias() string { return r.runEventDo.Alias() }

func (r runEvent) Columns(cols ...field.Expr) gen.Columns { return r.runEventDo.Columns(cols...) }

func (r *runEvent) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *runEvent) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 6)
	r.fieldMap["id"] = r.ID
	r.fieldMap["run_id"] = r.RunID
	r.fieldMap["seq"] = r.Seq
	r.fieldMap["type"] = r.Type
	r.fieldMap["safe_payload"] = r.SafePayload
	r.fieldMap["created_at"] = r.CreatedAt
}

func (r runEvent) clone(db *gorm.DB) runEvent {
	r.runEventDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r runEvent) replaceDB(db *gorm.DB) runEvent {
	r.runEventDo.ReplaceDB(db)
	return r
}

type runEventDo struct {
	gen.GenericsDo[IRunEventDo, *model.RunEvent]
}
type IRunEventDo interface {
	gen.IGenericsDo[IRunEventDo, *model.RunEvent]
}

func (r *runEventDo) withDO(do gen.Dao) IRunEventDo {
	_r := &runEventDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IRunEventDo](r.withDO)
	return _r
}
