// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"github.com/patrhez/agent-platform/backend/internal/model"
	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"
)

func newRunStep(db *gorm.DB, opts ...gen.DOOption) runStep {
	_runStep := runStep{}

	_runStep.runStepDo.IWithDO = gen.WithDOFunc[IRunStepDo](_runStep.runStepDo.withDO)

	_runStep.runStepDo.UseDB(db, opts...)
	_runStep.runStepDo.UseModel(&model.RunStep{})

	tableName := _runStep.runStepDo.TableName()
	_runStep.ALL = field.NewAsterisk(tableName)
	_runStep.ID = field.NewString(tableName, "id")
	_runStep.RunID = field.NewString(tableName, "run_id")
	_runStep.StepNo = field.NewInt(tableName, "step_no")
	_runStep.Kind = field.NewString(tableName, "kind")
	_runStep.Status = field.NewString(tableName, "status")
	_runStep.SafeSummary = field.NewString(tableName, "safe_summary")
	_runStep.StartedAt = field.NewTime(tableName, "started_at")
	_runStep.FinishedAt = field.NewTime(tableName, "finished_at")
	_runStep.CreatedAt = field.NewTime(tableName, "created_at")

	_runStep.fillFieldMap()

	return _runStep
}

type runStep struct {
	runStepDo runStepDo

	ALL         field.Asterisk
	ID          field.String
	RunID       field.String
	StepNo      field.Int
	Kind        field.String
	Status      field.String
	SafeSummary field.String
	StartedAt   field.Time
	FinishedAt  field.Time
	CreatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (r runStep) Table(newTableName string) *runStep {
	r.runStepDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r runStep) As(alias string) *runStep {
	r.runStepDo.DO = *(r.runStepDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *runStep) updateTableName(table string) *runStep {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewString(table, "id")
	r.RunID = field.NewString(table, "run_id")
	r.StepNo = field.NewInt(table, "step_no")
	r.Kind = field.NewString(table, "kind")
	r.Status = field.NewString(table, "status")
	r.SafeSummary = field.NewString(table, "safe_summary")
	r.StartedAt = field.NewTime(table, "started_at")
	r.FinishedAt = field.NewTime(table, "finished_at")
	r.CreatedAt = field.NewTime(table, "created_at")

	r.fillFieldMap()

	return r
}

func (r *runStep) WithContext(ctx context.Context) IRunStepDo { return r.runStepDo.WithContext(ctx) }

func (r runStep) TableName() string { return r.runStepDo.TableName() }

func (r runStep) Alias() string { return r.runStepDo.Alias() }

func (r runStep) Columns(cols ...field.Expr) gen.Columns { return r.runStepDo.Columns(cols...) }

func (r *runStep) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *runStep) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 9)
	r.fieldMap["id"] = r.ID
	r.fieldMap["run_id"] = r.RunID
	r.fieldMap["step_no"] = r.StepNo
	r.fieldMap["kind"] = r.Kind
	r.fieldMap["status"] = r.Status
	r.fieldMap["safe_summary"] = r.SafeSummary
	r.fieldMap["started_at"] = r.StartedAt
	r.fieldMap["finished_at"] = r.FinishedAt
	r.fieldMap["created_at"] = r.CreatedAt
}

func (r runStep) clone(db *gorm.DB) runStep {
	r.runStepDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r runStep) replaceDB(db *gorm.DB) runStep {
	r.runStepDo.ReplaceDB(db)
	return r
}

type runStepDo struct {
	gen.GenericsDo[IRunStepDo, *model.RunStep]
}
type IRunStepDo interface {
	gen.IGenericsDo[IRunStepDo, *model.RunStep]
}

func (r *runStepDo) withDO(do gen.Dao) IRunStepDo {
	_r := &runStepDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IRunStepDo](r.withDO)
	return _r
}
