// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"github.com/patrhez/agent-platform/backend/internal/model"
	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"
)

func newRun(db *gorm.DB, opts ...gen.DOOption) run {
	_run := run{}

	_run.runDo.IWithDO = gen.WithDOFunc[IRunDo](_run.runDo.withDO)

	_run.runDo.UseDB(db, opts...)
	_run.runDo.UseModel(&model.Run{})

	tableName := _run.runDo.TableName()
	_run.ALL = field.NewAsterisk(tableName)
	_run.ID = field.NewString(tableName, "id")
	_run.ConversationID = field.NewString(tableName, "conversation_id")
	_run.TriggerMessageID = field.NewString(tableName, "trigger_message_id")
	_run.QueueSeq = field.NewInt64(tableName, "queue_seq")
	_run.Status = field.NewString(tableName, "status")
	_run.Attempt = field.NewInt(tableName, "attempt")
	_run.NextAttemptAt = field.NewTime(tableName, "next_attempt_at")
	_run.LeaseOwner = field.NewString(tableName, "lease_owner")
	_run.LeaseExpiresAt = field.NewTime(tableName, "lease_expires_at")
	_run.ExecutionToken = field.NewInt64(tableName, "execution_token")
	_run.AgentConfigVersion = field.NewString(tableName, "agent_config_version")
	_run.SkillsBundleVersion = field.NewString(tableName, "skills_bundle_version")
	_run.ModelConfig = field.NewField(tableName, "model_config")
	_run.WorkspaceRef = field.NewField(tableName, "workspace_ref")
	_run.LatestCheckpointID = field.NewString(tableName, "latest_checkpoint_id")
	_run.NextEventSeq = field.NewInt64(tableName, "next_event_seq")
	_run.CancelRequestedAt = field.NewTime(tableName, "cancel_requested_at")
	_run.TerminalErrorCode = field.NewString(tableName, "terminal_error_code")
	_run.TerminalErrorMessage = field.NewString(tableName, "terminal_error_message")
	_run.StartedAt = field.NewTime(tableName, "started_at")
	_run.FinishedAt = field.NewTime(tableName, "finished_at")
	_run.CreatedAt = field.NewTime(tableName, "created_at")
	_run.UpdatedAt = field.NewTime(tableName, "updated_at")

	_run.fillFieldMap()

	return _run
}

type run struct {
	runDo runDo

	ALL                  field.Asterisk
	ID                   field.String
	ConversationID       field.String
	TriggerMessageID     field.String
	QueueSeq             field.Int64
	Status               field.String
	Attempt              field.Int
	NextAttemptAt        field.Time
	LeaseOwner           field.String
	LeaseExpiresAt       field.Time
	ExecutionToken       field.Int64
	AgentConfigVersion   field.String
	SkillsBundleVersion  field.String
	ModelConfig          field.Field
	WorkspaceRef         field.Field
	LatestCheckpointID   field.String
	NextEventSeq         field.Int64
	CancelRequestedAt    field.Time
	TerminalErrorCode    field.String
	TerminalErrorMessage field.String
	StartedAt            field.Time
	FinishedAt           field.Time
	CreatedAt            field.Time
	UpdatedAt            field.Time

	fieldMap map[string]field.Expr
}

func (r run) Table(newTableName string) *run {
	r.runDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r run) As(alias string) *run {
	r.runDo.DO = *(r.runDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *run) updateTableName(table string) *run {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewString(table, "id")
	r.ConversationID = field.NewString(table, "conversation_id")
	r.TriggerMessageID = field.NewString(table, "trigger_message_id")
	r.QueueSeq = field.NewInt64(table, "queue_seq")
	r.Status = field.NewString(table, "status")
	r.Attempt = field.NewInt(table, "attempt")
	r.NextAttemptAt = field.NewTime(table, "next_attempt_at")
	r.LeaseOwner = field.NewString(table, "lease_owner")
	r.LeaseExpiresAt = field.NewTime(table, "lease_expires_at")
	r.ExecutionToken = field.NewInt64(table, "execution_token")
	r.AgentConfigVersion = field.NewString(table, "agent_config_version")
	r.SkillsBundleVersion = field.NewString(table, "skills_bundle_version")
	r.ModelConfig = field.NewField(table, "model_config")
	r.WorkspaceRef = field.NewField(table, "workspace_ref")
	r.LatestCheckpointID = field.NewString(table, "latest_checkpoint_id")
	r.NextEventSeq = field.NewInt64(table, "next_event_seq")
	r.CancelRequestedAt = field.NewTime(table, "cancel_requested_at")
	r.TerminalErrorCode = field.NewString(table, "terminal_error_code")
	r.TerminalErrorMessage = field.NewString(table, "terminal_error_message")
	r.StartedAt = field.NewTime(table, "started_at")
	r.FinishedAt = field.NewTime(table, "finished_at")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")

	r.fillFieldMap()

	return r
}

func (r *run) WithContext(ctx context.Context) IRunDo { return r.runDo.WithContext(ctx) }

func (r run) TableName() string { return r.runDo.TableName() }

func (r run) Alias() string { return r.runDo.Alias() }

func (r run) Columns(cols ...field.Expr) gen.Columns { return r.runDo.Columns(cols...) }

func (r *run) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *run) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 23)
	r.fieldMap["id"] = r.ID
	r.fieldMap["conversation_id"] = r.ConversationID
	r.fieldMap["trigger_message_id"] = r.TriggerMessageID
	r.fieldMap["queue_seq"] = r.QueueSeq
	r.fieldMap["status"] = r.Status
	r.fieldMap["attempt"] = r.Attempt
	r.fieldMap["next_attempt_at"] = r.NextAttemptAt
	r.fieldMap["lease_owner"] = r.LeaseOwner
	r.fieldMap["lease_expires_at"] = r.LeaseExpiresAt
	r.fieldMap["execution_token"] = r.ExecutionToken
	r.fieldMap["agent_config_version"] = r.AgentConfigVersion
	r.fieldMap["skills_bundle_version"] = r.SkillsBundleVersion
	r.fieldMap["model_config"] = r.ModelConfig
	r.fieldMap["workspace_ref"] = r.WorkspaceRef
	r.fieldMap["latest_checkpoint_id"] = r.LatestCheckpointID
	r.fieldMap["next_event_seq"] = r.NextEventSeq
	r.fieldMap["cancel_requested_at"] = r.CancelRequestedAt
	r.fieldMap["terminal_error_code"] = r.TerminalErrorCode
	r.fieldMap["terminal_error_message"] = r.TerminalErrorMessage
	r.fieldMap["started_at"] = r.StartedAt
	r.fieldMap["finished_at"] = r.FinishedAt
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
}

func (r run) clone(db *gorm.DB) run {
	r.runDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r run) replaceDB(db *gorm.DB) run {
	r.runDo.ReplaceDB(db)
	return r
}

type runDo struct {
	gen.GenericsDo[IRunDo, *model.Run]
}
type IRunDo interface {
	gen.IGenericsDo[IRunDo, *model.Run]
}

func (r *runDo) withDO(do gen.Dao) IRunDo {
	_r := &runDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IRunDo](r.withDO)
	return _r
}
