// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"github.com/patrhez/agent-platform/backend/internal/model"
	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"
)

func newToolCall(db *gorm.DB, opts ...gen.DOOption) toolCall {
	_toolCall := toolCall{}

	_toolCall.toolCallDo.IWithDO = gen.WithDOFunc[IToolCallDo](_toolCall.toolCallDo.withDO)

	_toolCall.toolCallDo.UseDB(db, opts...)
	_toolCall.toolCallDo.UseModel(&model.ToolCall{})

	tableName := _toolCall.toolCallDo.TableName()
	_toolCall.ALL = field.NewAsterisk(tableName)
	_toolCall.ID = field.NewString(tableName, "id")
	_toolCall.RunID = field.NewString(tableName, "run_id")
	_toolCall.StepNo = field.NewInt(tableName, "step_no")
	_toolCall.ServerKey = field.NewString(tableName, "server_key")
	_toolCall.ToolName = field.NewString(tableName, "tool_name")
	_toolCall.Arguments = field.NewField(tableName, "arguments")
	_toolCall.ResultSummary = field.NewString(tableName, "result_summary")
	_toolCall.ArtifactID = field.NewString(tableName, "artifact_id")
	_toolCall.IdempotencyKey = field.NewString(tableName, "idempotency_key")
	_toolCall.Status = field.NewString(tableName, "status")
	_toolCall.CreatedAt = field.NewTime(tableName, "created_at")
	_toolCall.UpdatedAt = field.NewTime(tableName, "updated_at")

	_toolCall.fillFieldMap()

	return _toolCall
}

type toolCall struct {
	toolCallDo toolCallDo

	ALL            field.Asterisk
	ID             field.String
	RunID          field.String
	StepNo         field.Int
	ServerKey      field.String
	ToolName       field.String
	Arguments      field.Field
	ResultSummary  field.String
	ArtifactID     field.String
	IdempotencyKey field.String
	Status         field.String
	CreatedAt      field.Time
	UpdatedAt      field.Time

	fieldMap map[string]field.Expr
}

func (t toolCall) Table(newTableName string) *toolCall {
	t.toolCallDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t toolCall) As(alias string) *toolCall {
	t.toolCallDo.DO = *(t.toolCallDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *toolCall) updateTableName(table string) *toolCall {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewString(table, "id")
	t.RunID = field.NewString(table, "run_id")
	t.StepNo = field.NewInt(table, "step_no")
	t.ServerKey = field.NewString(table, "server_key")
	t.ToolName = field.NewString(table, "tool_name")
	t.Arguments = field.NewField(table, "arguments")
	t.ResultSummary = field.NewString(table, "result_summary")
	t.ArtifactID = field.NewString(table, "artifact_id")
	t.IdempotencyKey = field.NewString(table, "idempotency_key")
	t.Status = field.NewString(table, "status")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")

	t.fillFieldMap()

	return t
}

func (t *toolCall) WithContext(ctx context.Context) IToolCallDo { return t.toolCallDo.WithContext(ctx) }

func (t toolCall) TableName() string { return t.toolCallDo.TableName() }

func (t toolCall) Alias() string { return t.toolCallDo.Alias() }

func (t toolCall) Columns(cols ...field.Expr) gen.Columns { return t.toolCallDo.Columns(cols...) }

func (t *toolCall) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *toolCall) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 12)
	t.fieldMap["id"] = t.ID
	t.fieldMap["run_id"] = t.RunID
	t.fieldMap["step_no"] = t.StepNo
	t.fieldMap["server_key"] = t.ServerKey
	t.fieldMap["tool_name"] = t.ToolName
	t.fieldMap["arguments"] = t.Arguments
	t.fieldMap["result_summary"] = t.ResultSummary
	t.fieldMap["artifact_id"] = t.ArtifactID
	t.fieldMap["idempotency_key"] = t.IdempotencyKey
	t.fieldMap["status"] = t.Status
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
}

func (t toolCall) clone(db *gorm.DB) toolCall {
	t.toolCallDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t toolCall) replaceDB(db *gorm.DB) toolCall {
	t.toolCallDo.ReplaceDB(db)
	return t
}

type toolCallDo struct {
	gen.GenericsDo[IToolCallDo, *model.ToolCall]
}
type IToolCallDo interface {
	gen.IGenericsDo[IToolCallDo, *model.ToolCall]
}

func (t *toolCallDo) withDO(do gen.Dao) IToolCallDo {
	_r := &toolCallDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IToolCallDo](t.withDO)
	return _r
}
