// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"github.com/patrhez/agent-platform/backend/internal/model"
	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"
)

func newUser(db *gorm.DB, opts ...gen.DOOption) user {
	_user := user{}

	_user.userDo.IWithDO = gen.WithDOFunc[IUserDo](_user.userDo.withDO)

	_user.userDo.UseDB(db, opts...)
	_user.userDo.UseModel(&model.User{})

	tableName := _user.userDo.TableName()
	_user.ALL = field.NewAsterisk(tableName)
	_user.ID = field.NewString(tableName, "id")
	_user.TeamID = field.NewString(tableName, "team_id")
	_user.DisplayName = field.NewString(tableName, "display_name")
	_user.CreatedAt = field.NewTime(tableName, "created_at")

	_user.fillFieldMap()

	return _user
}

type user struct {
	userDo userDo

	ALL         field.Asterisk
	ID          field.String
	TeamID      field.String
	DisplayName field.String
	CreatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (u user) Table(newTableName string) *user {
	u.userDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u user) As(alias string) *user {
	u.userDo.DO = *(u.userDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *user) updateTableName(table string) *user {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewString(table, "id")
	u.TeamID = field.NewString(table, "team_id")
	u.DisplayName = field.NewString(table, "display_name")
	u.CreatedAt = field.NewTime(table, "created_at")

	u.fillFieldMap()

	return u
}

func (u *user) WithContext(ctx context.Context) IUserDo { return u.userDo.WithContext(ctx) }

func (u user) TableName() string { return u.userDo.TableName() }

func (u user) Alias() string { return u.userDo.Alias() }

func (u user) Columns(cols ...field.Expr) gen.Columns { return u.userDo.Columns(cols...) }

func (u *user) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *user) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 4)
	u.fieldMap["id"] = u.ID
	u.fieldMap["team_id"] = u.TeamID
	u.fieldMap["display_name"] = u.DisplayName
	u.fieldMap["created_at"] = u.CreatedAt
}

func (u user) clone(db *gorm.DB) user {
	u.userDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u user) replaceDB(db *gorm.DB) user {
	u.userDo.ReplaceDB(db)
	return u
}

type userDo struct {
	gen.GenericsDo[IUserDo, *model.User]
}
type IUserDo interface {
	gen.IGenericsDo[IUserDo, *model.User]
}

func (u *userDo) withDO(do gen.Dao) IUserDo {
	_r := &userDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IUserDo](u.withDO)
	return _r
}
